package com.github.fabriciolfj.study.service;

import com.anthropic.client.AnthropicClient;
import com.anthropic.core.http.HttpResponse;
import com.anthropic.models.beta.files.FileMetadata;
import com.github.fabriciolfj.study.dto.ReportRequest;
import com.github.fabriciolfj.study.model.AnthropicDocument;
import lombok.RequiredArgsConstructor;
import org.springframework.ai.anthropic.AnthropicChatModel;
import org.springframework.ai.anthropic.AnthropicChatOptions;
import org.springframework.ai.anthropic.AnthropicSkill;
import org.springframework.ai.anthropic.AnthropicSkillsResponseHelper;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.util.List;

@Service
@RequiredArgsConstructor
public class AgentSkillsService {

    private final AnthropicChatModel chatModel;
    private final MonthlySalesService monthlySalesService;

    public AnthropicDocument genReport(ReportRequest reportRequest) {
        ChatClient chatClient = ChatClient.builder(chatModel)
                .defaultOptions(AnthropicChatOptions.builder()
                        .model("claude-sonnet-4-5")
                        .skill("docx")
                        .skill("pdf")
                        .skill("pptx")
                        .skill("xlsx")
                        .maxTokens(8192)
                        .build().mutate())
                .build();

        ChatResponse response = chatClient.prompt()
                .system("Given the dataset of monthly sales: "
                        + monthlySalesService.getMonthlySalesForYear(2025))
                .user(reportRequest.prompt())
                .call()
                .chatResponse();
        List<String> fileIds = AnthropicSkillsResponseHelper.extractFileIds(response);
        if (fileIds.isEmpty()) {
            throw new IllegalStateException("No document was generated by the skill");
        }

        return downloadReport(fileIds.getFirst());
    }

    public AnthropicDocument downloadReport(String fileId) {
        AnthropicClient client = chatModel.getAnthropicClient();
        FileMetadata metadata = client.beta().files().retrieveMetadata(fileId);
        try (HttpResponse httpResponse = client.beta().files().download(fileId)) {
            byte[] content = httpResponse.body().readAllBytes();
            return new AnthropicDocument(metadata.filename(), metadata.mimeType(), content);
        } catch (IOException e) {
            throw new RuntimeException("Failed to download file: " + fileId, e);
        }
    }
}
